# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-06 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abrev', models.CharField(max_length=15, unique=True)),
                ('translate_name', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'believe_book',
                'default_permissions': (),
                'permissions': (('add_book', 'Puede agregar Book'), ('change_book', 'Puede actualizar Book'), ('delete_book', 'Puede eliminar Book'), ('list_book', 'Puede listar Book'), ('get_book', 'Puede obtener Book'), ('listform_book', 'Puede listar Book en Formularios')),
                'verbose_name_plural': 'Book',
                'verbose_name': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('translate_name', models.CharField(blank=True, max_length=30, null=True)),
                ('code_iso', models.CharField(default='ES', max_length=2, unique=True)),
            ],
            options={
                'db_table': 'believe_language',
                'default_permissions': (),
                'permissions': (('add_language', 'Puede agregar Language'), ('change_language', 'Puede actualizar Language'), ('delete_language', 'Puede eliminar Language'), ('list_language', 'Puede listar Language'), ('get_language', 'Puede obtener Language'), ('listform_language', 'Puede listar Language en Formularios')),
                'verbose_name_plural': 'Language',
                'verbose_name': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Testament',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abrev', models.CharField(max_length=15)),
                ('translate_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'believe_testament',
                'default_permissions': (),
                'permissions': (('add_testament', 'Puede agregar Testament'), ('change_testament', 'Puede actualizar Testament'), ('delete_testament', 'Puede eliminar Testament'), ('list_testament', 'Puede listar Testament'), ('get_testament', 'Puede obtener Testament'), ('listform_testament', 'Puede listar Testament en Formularios')),
                'verbose_name_plural': 'Testament',
                'verbose_name': 'Testament',
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('data', models.CharField(max_length=15, unique=True)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='believe_his_prophets.Book')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='believe_his_prophets.Language')),
            ],
            options={
                'db_table': 'believe_verse',
                'default_permissions': (),
                'permissions': (('add_verse', 'Puede agregar Verse'), ('change_verse', 'Puede actualizar Verse'), ('delete_verse', 'Puede eliminar Verse'), ('list_verse', 'Puede listar Verse'), ('get_verse', 'Puede obtener Verse'), ('listform_verse', 'Puede listar Verse en Formularios')),
                'verbose_name_plural': 'Verse',
                'verbose_name': 'Verse',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abrev', models.CharField(max_length=15)),
                ('translate_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'believe_version',
                'default_permissions': (),
                'permissions': (('add_version', 'Puede agregar Version'), ('change_version', 'Puede actualizar Version'), ('delete_version', 'Puede eliminar Version'), ('list_version', 'Puede listar Version'), ('get_version', 'Puede obtener Version'), ('listform_version', 'Puede listar Version en Formularios')),
                'verbose_name_plural': 'Version',
                'verbose_name': 'Version',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='testament',
            field=models.ForeignKey(db_column='testament_id', on_delete=django.db.models.deletion.CASCADE, to='believe_his_prophets.Testament'),
        ),
    ]
