# Generated by Django 2.0.9 on 2018-10-08 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisChapter',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('value', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
            ],
            options={
                'verbose_name': 'Analysis chapter',
                'verbose_name_plural': 'Analysis Chapter',
                'db_table': 'believe_analysis_chapter',
                'permissions': (('add_analysischapter', 'Puede agregar AnalysisChapter'), ('change_analysischapter', 'Puede actualizar AnalysisChapter'), ('delete_analysischapter', 'Puede eliminar AnalysisChapter'), ('list_analysischapter', 'Puede listar AnalysisChapter'), ('get_analysischapter', 'Puede obtener AnalysisChapter'), ('listform_analysischapter', 'Puede listar AnalysisChapter en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AnalysisVerse',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
            ],
            options={
                'verbose_name': 'Analysis verse',
                'verbose_name_plural': 'Analysis verse',
                'db_table': 'believe_sentimental',
                'permissions': (('add_analysisverse', 'Puede agregar AnalysisVerse'), ('change_analysisverse', 'Puede actualizar AnalysisVerse'), ('delete_analysisverse', 'Puede eliminar AnalysisVerse'), ('list_analysisverse', 'Puede listar AnalysisVerse'), ('get_analysisverse', 'Puede obtener AnalysisVerse'), ('listform_analysisverse', 'Puede listar AnalysisVerse en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
                ('content', models.TextField()),
                ('is_active', models.CharField(default='1', max_length=1)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Application',
                'db_table': 'believe_application',
                'ordering': ('version',),
                'permissions': (('add_application', 'Puede agregar Application'), ('change_application', 'Puede actualizar Application'), ('delete_application', 'Puede eliminar Application'), ('list_application', 'Puede listar Application'), ('get_application', 'Puede obtener Application'), ('listform_application', 'Puede listar Application en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BibleRead',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('start_chapter', models.IntegerField()),
                ('end_chapter', models.IntegerField()),
            ],
            options={
                'verbose_name': 'BibleRead',
                'verbose_name_plural': 'BibleRead',
                'db_table': 'bible_read',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('abrev', models.CharField(max_length=15)),
                ('translate_abrev', models.CharField(blank=True, max_length=50, null=True)),
                ('translate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('book_order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Book',
                'db_table': 'believe_book',
                'permissions': (('add_book', 'Puede agregar Book'), ('change_book', 'Puede actualizar Book'), ('delete_book', 'Puede eliminar Book'), ('list_book', 'Puede listar Book'), ('get_book', 'Puede obtener Book'), ('listform_book', 'Puede listar Book en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BookLanguage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('abreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Book')),
            ],
            options={
                'verbose_name': 'Book language',
                'verbose_name_plural': 'Book language',
                'db_table': 'believe_book_lang',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
                ('commentary_html', models.TextField(blank=True, null=True)),
                ('commentary', models.NullBooleanField()),
                ('commentary_file', models.FileField(blank=True, null=True, upload_to='')),
                ('commentary_url', models.CharField(blank=True, max_length=500, null=True)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Book')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapter',
                'db_table': 'believe_chapter',
                'ordering': ('book__book_order', 'chapter'),
                'permissions': (('add_chapter', 'Puede agregar Chapter'), ('change_chapter', 'Puede actualizar Chapter'), ('delete_chapter', 'Puede eliminar Chapter'), ('list_chapter', 'Puede listar Chapter'), ('get_chapter', 'Puede obtener Chapter'), ('listform_chapter', 'Puede listar Chapter en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('book', models.ForeignKey(db_column='verse_id', on_delete=django.db.models.deletion.PROTECT, related_name='book_commentary_set', to='believe_his_prophets.Book')),
            ],
            options={
                'verbose_name': 'Commentary',
                'verbose_name_plural': 'Commentary',
                'db_table': 'believe_commentary',
                'ordering': ('book__book_order', 'chapter'),
                'permissions': (('add_commentary', 'Puede agregar Commentary'), ('change_commentary', 'Puede actualizar Commentary'), ('delete_commentary', 'Puede eliminar Commentary'), ('list_commentary', 'Puede listar Commentary'), ('get_commentary', 'Puede obtener Commentary'), ('listform_commentary', 'Puede listar Commentary en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CommentaryVerse',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('word', models.CharField(max_length=150)),
                ('data', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'CommentaryVerse',
                'verbose_name_plural': 'CommentaryVerse',
                'db_table': 'believe_commentary_verse',
                'ordering': ('verse__book__book_order', 'verse__chapter', 'verse__verse', 'order'),
                'permissions': (('add_commentaryverse', 'Puede agregar CommentaryVerse'), ('change_commentaryverse', 'Puede actualizar CommentaryVerse'), ('delete_commentaryverse', 'Puede eliminar CommentaryVerse'), ('list_commentaryverse', 'Puede listar CommentaryVerse'), ('get_commentaryverse', 'Puede obtener CommentaryVerse'), ('listform_commentaryverse', 'Puede listar CommentaryVerse en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=350, null=True)),
            ],
            options={
                'verbose_name': 'Emotion',
                'verbose_name_plural': 'Emotion',
                'db_table': 'believe_emotion',
                'permissions': (('add_emotion', 'Puede agregar Emotion'), ('change_emotion', 'Puede actualizar Emotion'), ('delete_emotion', 'Puede eliminar Emotion'), ('list_emotion', 'Puede listar Emotion'), ('get_emotion', 'Puede obtener Emotion'), ('listform_emotion', 'Puede listar Emotion en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EmotionAnalysisChapter',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('analysis_chapter', models.ForeignKey(db_column='analysis_chapter_id', on_delete=django.db.models.deletion.PROTECT, related_name='analysis_chapter_emotion_analysis_chapter_set', to='believe_his_prophets.AnalysisChapter')),
                ('emotion', models.ForeignKey(db_column='emotion_id', on_delete=django.db.models.deletion.PROTECT, related_name='emotion_emotion_analysis_chapter_set', to='believe_his_prophets.Emotion')),
            ],
            options={
                'verbose_name': 'EmotionAnalysisChapter',
                'verbose_name_plural': 'EmotionAnalysisChapter',
                'db_table': 'believe_em_an_chapter',
                'permissions': (('add_emotionanalysischapter', 'Puede agregar EmotionAnalysisChapter'), ('change_emotionanalysischapter', 'Puede actualizar EmotionAnalysisChapter'), ('delete_emotionanalysischapter', 'Puede eliminar EmotionAnalysisChaper'), ('list_emotionanalysischapter', 'Puede listar EmotionAnalysisChapter'), ('get_emotionanalysischapter', 'Puede obtener EmotionAnalysisChapter'), ('listform_emotionanalysischapter', 'Puede listar EmotionAnalysisChapter en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EmotionAnalysisVerse',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('analysis_verse', models.ForeignKey(db_column='analysis_verse_id', on_delete=django.db.models.deletion.PROTECT, related_name='analysis_verse_emotion_analysis_verse_set', to='believe_his_prophets.AnalysisVerse')),
                ('emotion', models.ForeignKey(db_column='emotion_id', on_delete=django.db.models.deletion.PROTECT, related_name='emotion_emotion_analysis_verse_set', to='believe_his_prophets.Emotion')),
            ],
            options={
                'verbose_name': 'EmotionAnalysisVerse',
                'verbose_name_plural': 'EmotionAnalysisVerse',
                'db_table': 'believe_em_an_verse',
                'permissions': (('add_emotionanalysisverse', 'Puede agregar EmotionAnalysisVerse'), ('change_emotionanalysisverse', 'Puede actualizar EmotionAnalysisVerse'), ('delete_emotionanalysisverse', 'Puede eliminar EmotionAnalysisVerse'), ('list_emotionanalysisverse', 'Puede listar EmotionAnalysisVerse'), ('get_emotionanalysisverse', 'Puede obtener EmotionAnalysisVerse'), ('listform_emotionanalysisverse', 'Puede listar EmotionAnalysisVerse en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('translate_name', models.CharField(blank=True, max_length=30, null=True)),
                ('code_iso', models.CharField(default='ES', max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Language',
                'db_table': 'believe_language',
                'permissions': (('add_language', 'Puede agregar Language'), ('change_language', 'Puede actualizar Language'), ('delete_language', 'Puede eliminar Language'), ('list_language', 'Puede listar Language'), ('get_language', 'Puede obtener Language'), ('listform_language', 'Puede listar Language en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LanguageEmotion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('emotion', models.ForeignKey(db_column='emotion_id', on_delete=django.db.models.deletion.PROTECT, related_name='emotion_language_emotion_set', to='believe_his_prophets.Emotion')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, related_name='language_language_emotion_set', to='believe_his_prophets.Language')),
            ],
            options={
                'verbose_name': 'LanguageEmotion',
                'verbose_name_plural': 'LanguageEmotion',
                'db_table': 'believe_lan_emotion',
                'permissions': (('add_languageemotion', 'Puede agregar LanguageEmotion'), ('change_languageemotion', 'Puede actualizar LanguageEmotion'), ('delete_languageemotion', 'Puede eliminar LanguageEmotion'), ('list_languageemotion', 'Puede listar LanguageEmotion'), ('get_languageemotion', 'Puede obtener LanguageEmotion'), ('listform_languageemotion', 'Puede listar LanguageEmotion en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LanguageSentiment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, related_name='language_language_sentiment_set', to='believe_his_prophets.Language')),
            ],
            options={
                'verbose_name': 'LanguageSentiment',
                'verbose_name_plural': 'LanguageSentiment',
                'db_table': 'believe_lan_sentiment',
                'permissions': (('add_languagesentiment', 'Puede agregar LanguageSentiment'), ('change_languagesentiment', 'Puede actualizar LanguageSentiment'), ('delete_languagesentimentn', 'Puede eliminar LanguageSentiment'), ('list_languagesentiment', 'Puede listar LanguageSentiment'), ('get_languagesentiment', 'Puede obtener LanguageSentiment'), ('listform_languagesentiment', 'Puede listar LanguageSentiment en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=350, null=True)),
                ('language', models.ManyToManyField(related_name='language_sentiment_set', through='believe_his_prophets.LanguageSentiment', to='believe_his_prophets.Language', verbose_name='LanguageSentiment')),
            ],
            options={
                'verbose_name': 'Sentiment',
                'verbose_name_plural': 'Sentiment',
                'db_table': 'believe_sentiment',
                'permissions': (('add_sentiment', 'Puede agregar Sentiment'), ('change_sentiment', 'Puede actualizar Sentiment'), ('delete_sentiment', 'Puede eliminar Sentiment'), ('list_sentiment', 'Puede listar Sentiment'), ('get_sentiment', 'Puede obtener Sentiment'), ('listform_sentiment', 'Puede listar Sentiment en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SpiritProphecy',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('abrev', models.CharField(blank=True, max_length=15, null=True)),
                ('translate_abrev', models.CharField(blank=True, max_length=50, null=True)),
                ('translate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Language')),
            ],
            options={
                'verbose_name': 'SpiritProphecy',
                'verbose_name_plural': 'SpiritProphecy',
                'db_table': 'believe_spirit_prophecy',
                'permissions': (('add_spiritprophecy', 'Puede agregar SpiritProphecy'), ('change_spiritprophecy', 'Puede actualizar SpiritProphecy'), ('delete_spiritprophecy', 'Puede eliminar SpiritProphecy'), ('list_spiritprophecy', 'Puede listar SpiritProphecy'), ('get_spiritprophecy', 'Puede obtener SpiritProphecy'), ('listform_spiritprophecy', 'Puede listar SpiritProphecy en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SpiritProphecyChapter',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('translate_abrev', models.CharField(blank=True, max_length=50, null=True)),
                ('translate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Language')),
                ('spirit_prophecy', models.ForeignKey(db_column='spirit_prophecy_id', on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.SpiritProphecy')),
            ],
            options={
                'verbose_name': 'SpiritProphecyChapter',
                'verbose_name_plural': 'SpiritProphecyChapter',
                'db_table': 'believe_spirit_prophecy_chapter',
                'permissions': (('add_spiritprophecy', 'Puede agregar SpiritProphecyChapter'), ('change_spiritprophecy', 'Puede actualizar SpiritProphecyChapter'), ('delete_spiritprophecy', 'Puede eliminar SpiritProphecyChapter'), ('list_spiritprophecy', 'Puede listar SpiritProphecyChapter'), ('get_spiritprophecy', 'Puede obtener SpiritProphecyChapter'), ('listform_spiritprophecy', 'Puede listar SpiritProphecyChapter en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SpiritProphecyRead',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('date_read', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('chapter_title', models.CharField(blank=True, max_length=120, null=True)),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Language')),
                ('spirit_prophecy', models.ForeignKey(db_column='spirit_prophecy_id', on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.SpiritProphecy')),
                ('spirit_prophecy_chapter', models.ForeignKey(blank=True, db_column='spirit_prophecy_chapter_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.SpiritProphecyChapter')),
            ],
            options={
                'verbose_name': 'SpiritProphecyRead',
                'verbose_name_plural': 'SpiritProphecyRead',
                'db_table': 'believe_spirit_prophecy_read',
                'permissions': (('add_spiritprophecy', 'Puede agregar SpiritProphecyRead'), ('change_spiritprophecy', 'Puede actualizar SpiritProphecyRead'), ('delete_spiritprophecy', 'Puede eliminar SpiritProphecyRead'), ('list_spiritprophecy', 'Puede listar SpiritProphecyRead'), ('get_spiritprophecy', 'Puede obtener SpiritProphecyRead'), ('listform_spiritprophecy', 'Puede listar SpiritProphecyRead en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Testament',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abrev', models.CharField(max_length=20)),
                ('translate_abrev', models.CharField(max_length=50)),
                ('translate_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Testament',
                'verbose_name_plural': 'Testament',
                'db_table': 'believe_testament',
                'permissions': (('add_testament', 'Puede agregar Testament'), ('change_testament', 'Puede actualizar Testament'), ('delete_testament', 'Puede eliminar Testament'), ('list_testament', 'Puede listar Testament'), ('get_testament', 'Puede obtener Testament'), ('listform_testament', 'Puede listar Testament en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('data', models.TextField()),
                ('highlight', models.IntegerField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Book')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Language')),
            ],
            options={
                'verbose_name': 'Verse',
                'verbose_name_plural': 'Verse',
                'db_table': 'believe_verse',
                'ordering': ('book__book_order', 'chapter', 'verse'),
                'permissions': (('add_verse', 'Puede agregar Verse'), ('change_verse', 'Puede actualizar Verse'), ('delete_verse', 'Puede eliminar Verse'), ('list_verse', 'Puede listar Verse'), ('get_verse', 'Puede obtener Verse'), ('listform_verse', 'Puede listar Verse en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abrev', models.CharField(max_length=15)),
                ('translate_abrev', models.CharField(max_length=50)),
                ('translate_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Version',
                'db_table': 'believe_version',
                'permissions': (('add_version', 'Puede agregar Version'), ('change_version', 'Puede actualizar Version'), ('delete_version', 'Puede eliminar Version'), ('list_version', 'Puede listar Version'), ('get_version', 'Puede obtener Version'), ('listform_version', 'Puede listar Version en Formularios')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='languagesentiment',
            name='sentiment',
            field=models.ForeignKey(db_column='sentiment_id', on_delete=django.db.models.deletion.PROTECT, related_name='sentiment_language_sentiment_set', to='believe_his_prophets.Sentiment'),
        ),
        migrations.AddField(
            model_name='emotion',
            name='language',
            field=models.ManyToManyField(related_name='language_emotion_set', through='believe_his_prophets.LanguageEmotion', to='believe_his_prophets.Language', verbose_name='LanguageEmotion'),
        ),
        migrations.AddField(
            model_name='commentaryverse',
            name='verse',
            field=models.ForeignKey(db_column='verse_id', on_delete=django.db.models.deletion.PROTECT, related_name='commentary_verse_verse_set', to='believe_his_prophets.Verse'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='language',
            field=models.ForeignKey(blank=True, db_column='language_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='language_commentary_set', to='believe_his_prophets.Language'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='language',
            field=models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Language'),
        ),
        migrations.AddField(
            model_name='booklanguage',
            name='language',
            field=models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='testament',
            field=models.ForeignKey(db_column='testament_id', on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Testament'),
        ),
        migrations.AddField(
            model_name='bibleread',
            name='book',
            field=models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Book'),
        ),
        migrations.AddField(
            model_name='application',
            name='language',
            field=models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Language'),
        ),
        migrations.AddField(
            model_name='analysisverse',
            name='emotion',
            field=models.ManyToManyField(related_name='emotion_analysis_verse_set', through='believe_his_prophets.EmotionAnalysisVerse', to='believe_his_prophets.Emotion', verbose_name='EmotionAnalysisVerse'),
        ),
        migrations.AddField(
            model_name='analysisverse',
            name='sentiment',
            field=models.ForeignKey(blank=True, db_column='sentiment_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Sentiment'),
        ),
        migrations.AddField(
            model_name='analysisverse',
            name='verse',
            field=models.ForeignKey(db_column='verse_id', on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Verse'),
        ),
        migrations.AddField(
            model_name='analysischapter',
            name='book',
            field=models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Book'),
        ),
        migrations.AddField(
            model_name='analysischapter',
            name='emotion',
            field=models.ManyToManyField(related_name='emotion_analysis_chapter_set', through='believe_his_prophets.EmotionAnalysisChapter', to='believe_his_prophets.Emotion', verbose_name='EmotionAnalysisChapter'),
        ),
        migrations.AddField(
            model_name='analysischapter',
            name='sentiment',
            field=models.ForeignKey(blank=True, db_column='sentiment_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='believe_his_prophets.Sentiment'),
        ),
        migrations.AlterUniqueTogether(
            name='languagesentiment',
            unique_together={('sentiment', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='languageemotion',
            unique_together={('emotion', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='emotionanalysisverse',
            unique_together={('emotion', 'analysis_verse')},
        ),
        migrations.AlterUniqueTogether(
            name='emotionanalysischapter',
            unique_together={('emotion', 'analysis_chapter')},
        ),
    ]
