# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-06 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testament',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
