# Generated by Django 2.0.9 on 2018-11-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0002_auto_20181021_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='hierarchy_type',
        ),
        migrations.RemoveField(
            model_name='hierarchy',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='hierarchy',
            name='hierarchy_type',
        ),
        migrations.RemoveField(
            model_name='hierarchy',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='hierarchy',
            name='sucursal',
        ),
        migrations.DeleteModel(
            name='Entidad',
        ),
        migrations.DeleteModel(
            name='Hierarchy',
        ),
        migrations.DeleteModel(
            name='HierarchyType',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
