# Generated by Django 2.0.9 on 2018-11-05 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0003_auto_20181105_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiritProphecyLanguage',
            fields=[
                ('id', models.AutoField(editable=False,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('translate_abrev', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('translate_name', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT,
                                               related_name='spirit_prophecy_language_language_set', to='believe_his_prophets.Language')),
            ],
            options={
                'verbose_name': 'SpiritProphecyLanguage',
                'verbose_name_plural': 'SpiritProphecyLanguage',
                'db_table': 'believe_spirit_prophecy_lang',
            },
        ),
        migrations.AlterModelOptions(
            name='spiritprophecy',
            options={'verbose_name': 'SpiritProphecy',
                     'verbose_name_plural': 'SpiritProphecy'},
        ),
        migrations.RenameField(
            model_name='spiritprophecyread',
            old_name='date_read',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='spiritprophecy',
            name='abrev',
        ),
        migrations.RemoveField(
            model_name='spiritprophecy',
            name='translate_abrev',
        ),
        migrations.RemoveField(
            model_name='spiritprophecy',
            name='translate_name',
        ),
        migrations.RemoveField(
            model_name='spiritprophecyread',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='spiritprophecyread',
            name='chapter_title',
        ),
        migrations.RemoveField(
            model_name='spiritprophecyread',
            name='spirit_prophecy',
        ),
        migrations.RemoveField(
            model_name='spiritprophecyread',
            name='title',
        ),
        migrations.RemoveField(
            model_name='spiritprophecy',
            name='language',
        ),
        migrations.AlterField(
            model_name='spiritprophecy',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='spiritprophecylanguage',
            name='spirit_prophecy',
            field=models.ForeignKey(db_column='spirit_prophecy_id', on_delete=django.db.models.deletion.PROTECT,
                                    related_name='spirit_prophecy_language_spirit_prophecy_set', to='believe_his_prophets.SpiritProphecy'),
        ),
        migrations.AddField(
            model_name='spiritprophecy',
            name='language',
            field=models.ManyToManyField(
                blank=True, related_name='spirit_prophecy_language_set', to='believe_his_prophets.SpiritProphecyLanguage'),
        ),
    ]
