# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-06 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0003_auto_20170506_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translate_abrev',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testament',
            name='translate_abrev',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='translate_abrev',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='translate_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testament',
            name='abrev',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='testament',
            name='translate_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='translate_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
