# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-06 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0004_auto_20170506_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='order',
            new_name='book_order',
        ),
    ]
