# Generated by Django 2.0.9 on 2018-11-05 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0004_auto_20181105_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spiritprophecy',
            name='language',
        ),
    ]
