# Generated by Django 2.0.9 on 2018-11-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0005_remove_spiritprophecy_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiritprophecy',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='spirit_prophecy_language_set', through='believe_his_prophets.SpiritProphecyLanguage', to='believe_his_prophets.Language'),
        ),
    ]
