# Generated by Django 2.0.9 on 2018-11-06 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0006_spiritprophecy_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiritProphecyChapterLanguage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, related_name='spirit_prophecy_chapter_language_language_set', to='believe_his_prophets.Language')),
            ],
            options={
                'verbose_name': 'SpiritProphecyChapterLanguage',
                'verbose_name_plural': 'SpiritProphecyChapterLanguage',
                'db_table': 'believe_spirit_pr_lang_chapter',
            },
        ),
        migrations.AlterModelOptions(
            name='spiritprophecychapter',
            options={'verbose_name': 'SpiritProphecyChapter', 'verbose_name_plural': 'SpiritProphecyChapter'},
        ),
        migrations.AlterModelOptions(
            name='spiritprophecyread',
            options={'verbose_name': 'SpiritProphecyRead', 'verbose_name_plural': 'SpiritProphecyRead'},
        ),
        migrations.RemoveField(
            model_name='spiritprophecychapter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='spiritprophecychapter',
            name='translate_abrev',
        ),
        migrations.RemoveField(
            model_name='spiritprophecychapter',
            name='translate_name',
        ),
        migrations.RemoveField(
            model_name='spiritprophecychapter',
            name='language',
        ),
        migrations.AddField(
            model_name='spiritprophecychapterlanguage',
            name='spirit_prophecy_chapter',
            field=models.ForeignKey(db_column='spirit_prophecy_chapter_id', on_delete=django.db.models.deletion.PROTECT, related_name='spirit_prophecy_chapter_language_spirit_prophecy_chapter_set', to='believe_his_prophets.SpiritProphecyChapter'),
        ),
        migrations.AddField(
            model_name='spiritprophecychapter',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='spirit_prophecy_language_chapter_set', through='believe_his_prophets.SpiritProphecyChapterLanguage', to='believe_his_prophets.Language'),
        ),
    ]
