# Generated by Django 2.0.9 on 2018-11-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0007_auto_20181106_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklanguage',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booklanguage',
            name='language',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Book'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='abrev',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='translate_abrev',
        ),
        migrations.RemoveField(
            model_name='book',
            name='translate_name',
        ),
        migrations.AlterModelTable(
            name='spiritprophecychapterlanguage',
            table='believe_spirit_pr_chapter_lang',
        ),
        migrations.DeleteModel(
            name='BookLanguage',
        ),
    ]
