# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-06 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0007_auto_20170506_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='highlight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
