# Generated by Django 2.0.9 on 2018-11-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0008_auto_20181106_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLanguage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('abrev', models.CharField(blank=True, max_length=100, null=True)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.PROTECT, related_name='book_language_book_set', to='believe_his_prophets.Book')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, related_name='book_language_language_set', to='believe_his_prophets.Language')),
            ],
            options={
                'verbose_name': 'BookLanguage',
                'verbose_name_plural': 'BookLanguage',
                'db_table': 'believe_book_language',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='book_language_set', through='believe_his_prophets.BookLanguage', to='believe_his_prophets.Language'),
        ),
    ]
