# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-06 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0008_verse_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='data',
            field=models.TextField(),
        ),
    ]
