# Generated by Django 2.0.9 on 2018-11-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0009_auto_20181106_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiritprophecychapterlanguage',
            name='data',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
