# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-23 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0009_auto_20170506_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleRead',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('start_chapter', models.IntegerField()),
                ('end_chapter', models.IntegerField()),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='believe_his_prophets.Book')),
            ],
            options={
                'verbose_name_plural': 'BibleRead',
                'permissions': (('add_bibleread', 'Puede agregar BibleRead'), ('change_bibleread', 'Puede actualizar BibleRead'), ('delete_bibleread', 'Puede eliminar BibleRead'), ('list_bibleread', 'Puede listar BibleRead'), ('get_bibleread', 'Puede obtener BibleRead'), ('listform_bibleread', 'Puede listar BibleRead en Formularios')),
                'verbose_name': 'BibleRead',
                'db_table': 'bible_read',
                'default_permissions': (),
            },
        ),
    ]
