# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-10 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0010_bibleread'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiritProphecy',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('abrev', models.CharField(max_length=15)),
                ('translate_abrev', models.CharField(max_length=50)),
                ('translate_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'SpiritProphecy',
                'db_table': 'believe_spirit_prophecy',
                'permissions': (('add_spiritprophecy', 'Puede agregar SpiritProphecy'), ('change_spiritprophecy', 'Puede actualizar SpiritProphecy'), ('delete_spiritprophecy', 'Puede eliminar SpiritProphecy'), ('list_spiritprophecy', 'Puede listar SpiritProphecy'), ('get_spiritprophecy', 'Puede obtener SpiritProphecy'), ('listform_spiritprophecy', 'Puede listar SpiritProphecy en Formularios')),
                'default_permissions': (),
                'verbose_name_plural': 'SpiritProphecy',
            },
        ),
    ]
