# Generated by Django 2.0.9 on 2021-02-20 19:24

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0011_auto_20181106_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiritprophecychapterlanguage',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='audios/sp/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='audios/'),
        ),
    ]
