# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-10 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0011_spiritprophecy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiritProphecyChapter',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('abrev', models.CharField(max_length=15)),
                ('translate_abrev', models.CharField(max_length=50)),
                ('translate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('spirit_prophecy', models.ForeignKey(db_column='spirit_prophecy_id', on_delete=django.db.models.deletion.CASCADE, to='believe_his_prophets.SpiritProphecy')),
            ],
            options={
                'verbose_name_plural': 'SpiritProphecyChapter',
                'db_table': 'believe_spirit_prophecy_chapter',
                'verbose_name': 'SpiritProphecyChapter',
                'permissions': (('add_spiritprophecy', 'Puede agregar SpiritProphecyChapter'), ('change_spiritprophecy', 'Puede actualizar SpiritProphecyChapter'), ('delete_spiritprophecy', 'Puede eliminar SpiritProphecyChapter'), ('list_spiritprophecy', 'Puede listar SpiritProphecyChapter'), ('get_spiritprophecy', 'Puede obtener SpiritProphecyChapter'), ('listform_spiritprophecy', 'Puede listar SpiritProphecyChapter en Formularios')),
                'default_permissions': (),
            },
        ),
    ]
