# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-10 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0012_spiritprophecychapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiritprophecychapter',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
