# Generated by Django 2.0.9 on 2021-02-20 19:58

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0012_auto_20210220_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('audio', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='audios/')),
            ],
            options={
                'db_table': 'believe_file',
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
