# Generated by Django 2.0.9 on 2021-02-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0013_spiritprophecyread_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiritprophecychapter',
            name='archivo',
            field=models.FileField(default='test', upload_to='files/'),
            preserve_default=False,
        ),
    ]
