# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-10 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0014_remove_spiritprophecychapter_abrev'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiritProphecyRead',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('spirit_prophecy', models.ForeignKey(db_column='spirit_prophecy_id', on_delete=django.db.models.deletion.CASCADE, to='believe_his_prophets.SpiritProphecy')),
                ('spirit_prophecy_chapter', models.ForeignKey(db_column='spirit_prophecy_chapter_id', on_delete=django.db.models.deletion.CASCADE, to='believe_his_prophets.SpiritProphecyChapter')),
            ],
            options={
                'permissions': (('add_spiritprophecy', 'Puede agregar SpiritProphecyRead'), ('change_spiritprophecy', 'Puede actualizar SpiritProphecyRead'), ('delete_spiritprophecy', 'Puede eliminar SpiritProphecyRead'), ('list_spiritprophecy', 'Puede listar SpiritProphecyRead'), ('get_spiritprophecy', 'Puede obtener SpiritProphecyRead'), ('listform_spiritprophecy', 'Puede listar SpiritProphecyRead en Formularios')),
                'default_permissions': (),
                'verbose_name_plural': 'SpiritProphecyRead',
                'verbose_name': 'SpiritProphecyRead',
                'db_table': 'believe_spirit_prophecy_read',
            },
        ),
    ]
