# Generated by Django 2.0.9 on 2021-02-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0014_spiritprophecychapter_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiritprophecychapterlanguage',
            name='archivo',
            field=models.FileField(default='test', upload_to='files'),
            preserve_default=False,
        ),
    ]
