# Generated by Django 2.0.9 on 2021-02-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0015_spiritprophecychapterlanguage_archivo'),
        ('believe_his_prophets', '0013_file'),
    ]

    operations = [
    ]
