# Generated by Django 2.0.9 on 2021-02-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0016_merge_20210220_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='contenido',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
