# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-10 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0016_spiritprophecyread_date_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiritprophecychapter',
            name='chapter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
