# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-10 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0017_spiritprophecychapter_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiritprophecyread',
            name='language',
            field=models.ForeignKey(blank=True, db_column='language_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='believe_his_prophets.Language'),
        ),
    ]
