# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-17 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0018_spiritprophecyread_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
