# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-17 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0019_verse_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verse',
            options={'default_permissions': (), 'ordering': ('book__book_order', 'chapter', 'verse'), 'permissions': (('add_verse', 'Puede agregar Verse'), ('change_verse', 'Puede actualizar Verse'), ('delete_verse', 'Puede eliminar Verse'), ('list_verse', 'Puede listar Verse'), ('get_verse', 'Puede obtener Verse'), ('listform_verse', 'Puede listar Verse en Formularios')), 'verbose_name': 'Verse', 'verbose_name_plural': 'Verse'},
        ),
    ]
