# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-17 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0020_auto_20170617_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='believe_his_prophets.Book')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='believe_his_prophets.Language')),
            ],
            options={
                'db_table': 'believe_chapter',
                'verbose_name_plural': 'Chapter',
                'default_permissions': (),
                'verbose_name': 'Chapter',
                'ordering': ('book__book_order', 'chapter'),
                'permissions': (('add_chapter', 'Puede agregar Chapter'), ('change_chapter', 'Puede actualizar Chapter'), ('delete_chapter', 'Puede eliminar Chapter'), ('list_chapter', 'Puede listar Chapter'), ('get_chapter', 'Puede obtener Chapter'), ('listform_chapter', 'Puede listar Chapter en Formularios')),
            },
        ),
    ]
