# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-22 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0021_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='believe_his_prophets.Language')),
            ],
            options={
                'ordering': ('version',),
                'db_table': 'believe_application',
                'default_permissions': (),
                'verbose_name': 'Application',
                'permissions': (('add_application', 'Puede agregar Application'), ('change_application', 'Puede actualizar Application'), ('delete_application', 'Puede eliminar Application'), ('list_application', 'Puede listar Application'), ('get_application', 'Puede obtener Application'), ('listform_application', 'Puede listar Application en Formularios')),
                'verbose_name_plural': 'Application',
            },
        ),
    ]
