# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-22 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0022_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
