# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-22 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0023_application_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
