# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-06 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0024_application_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaryVerse',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('word', models.CharField(max_length=150)),
                ('data', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
                ('verse', models.ForeignKey(db_column='verse_id', on_delete=django.db.models.deletion.CASCADE, to='believe_his_prophets.Verse')),
            ],
            options={
                'default_permissions': (),
                'verbose_name_plural': 'CommentaryVerse',
                'permissions': (('add_commentaryverse', 'Puede agregar CommentaryVerse'), ('change_commentaryverse', 'Puede actualizar CommentaryVerse'), ('delete_commentaryverse', 'Puede eliminar CommentaryVerse'), ('list_commentaryverse', 'Puede listar CommentaryVerse'), ('get_commentaryverse', 'Puede obtener CommentaryVerse'), ('listform_commentaryverse', 'Puede listar CommentaryVerse en Formularios')),
                'db_table': 'believe_commentary_verse',
                'ordering': ('verse__book__book_order', 'verse__chapter', 'verse__verse'),
                'verbose_name': 'CommentaryVerse',
            },
        ),
    ]
