# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-07 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0025_commentaryverse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaryverse',
            options={'default_permissions': (), 'ordering': ('verse__book__book_order', 'verse__chapter', 'verse__verse', 'order'), 'permissions': (('add_commentaryverse', 'Puede agregar CommentaryVerse'), ('change_commentaryverse', 'Puede actualizar CommentaryVerse'), ('delete_commentaryverse', 'Puede eliminar CommentaryVerse'), ('list_commentaryverse', 'Puede listar CommentaryVerse'), ('get_commentaryverse', 'Puede obtener CommentaryVerse'), ('listform_commentaryverse', 'Puede listar CommentaryVerse en Formularios')), 'verbose_name': 'CommentaryVerse', 'verbose_name_plural': 'CommentaryVerse'},
        ),
        migrations.AlterField(
            model_name='commentaryverse',
            name='verse',
            field=models.ForeignKey(db_column='verse_id', on_delete=django.db.models.deletion.CASCADE, related_name='commentary_verse_verse_set', to='believe_his_prophets.Verse'),
        ),
    ]
