# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-09 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe_his_prophets', '0026_auto_20170707_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='commentary',
            field=models.NullBooleanField(),
        ),
    ]
